export const SYNC_SERVER_URL_KEY = 'SYNC_SERVER_URL';
export const SYNC_TABLE_NAME_KEY = 'SYNC_TABLE_NAME';
export const SYNC_SEMANTIC_EMBED_MODEL_KEY = 'SYNC_SEMANTIC_EMBED_MODEL';
export const SYNC_SIMILAR_EMBED_MODEL_KEY = 'SYNC_SIMILAR_EMBED_MODEL';

export const DEFAULT_SYNC_TABLE = 'posts';
export const DEFAULT_EMBED_MODEL = 'default';
export const DEFAULT_SYNC_INTERVAL_MS = 15 * 60 * 1000; // 15 minutes
